option casemap:none

.data
cpuid_buffer db 13 dup(0)

.code
public GetCpuVendorString
public MMX_emms
public MMX_movd_mm0_reg
public MMX_movd_mm1_reg
public MMX_movd_mm2_reg
public MMX_movd_mm3_reg
public MMX_movd_mm4_reg
public MMX_movd_mm5_reg
public MMX_movd_mm6_reg
public MMX_movd_mm7_reg
public MMX_movd_mm0_var
public MMX_movd_mm1_var
public MMX_movd_mm2_var
public MMX_movd_mm3_var
public MMX_movd_mm4_var
public MMX_movd_mm5_var
public MMX_movd_mm6_var
public MMX_movd_mm7_var
