#pragma once
extern "C" char* __stdcall GetCpuVendorString();
extern "C" void __stdcall MMX_movd_mm0_reg(int);
extern "C" void __stdcall MMX_movd_mm1_reg(int);
extern "C" void __stdcall MMX_movd_mm2_reg(int);
extern "C" void __stdcall MMX_movd_mm3_reg(int);
extern "C" void __stdcall MMX_movd_mm4_reg(int);
extern "C" void __stdcall MMX_movd_mm5_reg(int);
extern "C" void __stdcall MMX_movd_mm6_reg(int);
extern "C" void __stdcall MMX_movd_mm7_reg(int);
extern "C" void __stdcall MMX_movd_mm0_var(int*);
extern "C" void __stdcall MMX_movd_mm1_var(int*);
extern "C" void __stdcall MMX_movd_mm2_var(int*);
extern "C" void __stdcall MMX_movd_mm3_var(int*);
extern "C" void __stdcall MMX_movd_mm4_var(int*);
extern "C" void __stdcall MMX_movd_mm5_var(int*);
extern "C" void __stdcall MMX_movd_mm6_var(int*);
extern "C" void __stdcall MMX_movd_mm7_var(int*);
extern "C" void __stdcall MMX_emms();